---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: micros-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - kind.dev
        - minikube.dev
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: articles-vs
spec:
  hosts:
    - kind.dev
    - minikube.dev
  gateways:
    - micros-gateway
  http:
    - match:
        - uri:
            prefix: /articles
      rewrite:
        uri: /api/articles
      route:
        - destination:
            port:
              number: 3000
            host: articles-service.demo.svc.cluster.local
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: config-vs
spec:
  hosts:
    - kind.dev
    - minikube.dev
  gateways:
    - micros-gateway
  http:
    - match:
        - uri:
            prefix: /config
      rewrite:
        uri: /api/config
      route:
        - destination:
            port:
              number: 3001
            host: config-reader-service.demo.svc.cluster.local
---

