# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: article-service
# spec:
#   type: ExternalName
#   externalName: articles-service.demo.svc.cluster.local
# ---
# kind: Service
# apiVersion: v1
# metadata:
#   name: config-service
# spec:
#   type: ExternalName
#   externalName: config-reader-service.demo.svc.cluster.local
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
spec:
  rules:
    - http:
        paths:
          - path: /api/articles(/|$)(.*)
            backend:
              serviceName: articles-service
              servicePort: 3000
            path:
          - path: /api/config
            backend:
              serviceName: config-reader-service
              servicePort: 3001
