apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        service: mongo
    spec:
      containers:
        - image: mongo:latest
          imagePullPolicy: ''
          name: mongo-database
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
      serviceAccountName: ''
      volumes: null
status: {}
